### PR TITLE
Testing/3.3.11.1

### PR DESCRIPTION
**Pull request by SSE4**
testing and stable diverged significantly...

### CODE REVIEW

**Review by Croydon — APPROVED** [review]
According to the "files changed" tab, there are almost no changes, despite so many commits.....

LGTM, I guess?

**Comment by SSE4** [comment]
@Croydon  seems so :)

**Comment by Croydon** [comment]
I believe that if you rebase this only two commits will be actually new :)

**Comment by Croydon** [comment]
IIRC, this repository did have the entire history of our templates repository and I did cut that off, maybe your local branches are out of sync with that or something 🤔

**Comment by SSE4** [comment]
nope, this repository was forked from non-bincrafters repository

**Pull request merged**
